// Code generated by protoc-gen-go. DO NOT EDIT.
// source: relapse.proto

package relapse_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Capture struct {
	CaptureID             int64    `protobuf:"varint,1,opt,name=CaptureID,proto3" json:"CaptureID,omitempty"`
	AppName               string   `protobuf:"bytes,2,opt,name=AppName,proto3" json:"AppName,omitempty"`
	WindowTitle           string   `protobuf:"bytes,3,opt,name=WindowTitle,proto3" json:"WindowTitle,omitempty"`
	Filepath              string   `protobuf:"bytes,4,opt,name=Filepath,proto3" json:"Filepath,omitempty"`
	Fullpath              string   `protobuf:"bytes,5,opt,name=Fullpath,proto3" json:"Fullpath,omitempty"`
	CaptureTimeSeconds    int64    `protobuf:"varint,6,opt,name=CaptureTimeSeconds,proto3" json:"CaptureTimeSeconds,omitempty"`
	CaptureDayTimeSeconds int64    `protobuf:"varint,7,opt,name=CaptureDayTimeSeconds,proto3" json:"CaptureDayTimeSeconds,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Capture) Reset()         { *m = Capture{} }
func (m *Capture) String() string { return proto.CompactTextString(m) }
func (*Capture) ProtoMessage()    {}
func (*Capture) Descriptor() ([]byte, []int) {
	return fileDescriptor_faadcc3e9253be60, []int{0}
}

func (m *Capture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capture.Unmarshal(m, b)
}
func (m *Capture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capture.Marshal(b, m, deterministic)
}
func (m *Capture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capture.Merge(m, src)
}
func (m *Capture) XXX_Size() int {
	return xxx_messageInfo_Capture.Size(m)
}
func (m *Capture) XXX_DiscardUnknown() {
	xxx_messageInfo_Capture.DiscardUnknown(m)
}

var xxx_messageInfo_Capture proto.InternalMessageInfo

func (m *Capture) GetCaptureID() int64 {
	if m != nil {
		return m.CaptureID
	}
	return 0
}

func (m *Capture) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *Capture) GetWindowTitle() string {
	if m != nil {
		return m.WindowTitle
	}
	return ""
}

func (m *Capture) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *Capture) GetFullpath() string {
	if m != nil {
		return m.Fullpath
	}
	return ""
}

func (m *Capture) GetCaptureTimeSeconds() int64 {
	if m != nil {
		return m.CaptureTimeSeconds
	}
	return 0
}

func (m *Capture) GetCaptureDayTimeSeconds() int64 {
	if m != nil {
		return m.CaptureDayTimeSeconds
	}
	return 0
}

type DayRequest struct {
	CaptureDayTimeSeconds int64    `protobuf:"varint,1,opt,name=CaptureDayTimeSeconds,proto3" json:"CaptureDayTimeSeconds,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *DayRequest) Reset()         { *m = DayRequest{} }
func (m *DayRequest) String() string { return proto.CompactTextString(m) }
func (*DayRequest) ProtoMessage()    {}
func (*DayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_faadcc3e9253be60, []int{1}
}

func (m *DayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DayRequest.Unmarshal(m, b)
}
func (m *DayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DayRequest.Marshal(b, m, deterministic)
}
func (m *DayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DayRequest.Merge(m, src)
}
func (m *DayRequest) XXX_Size() int {
	return xxx_messageInfo_DayRequest.Size(m)
}
func (m *DayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DayRequest proto.InternalMessageInfo

func (m *DayRequest) GetCaptureDayTimeSeconds() int64 {
	if m != nil {
		return m.CaptureDayTimeSeconds
	}
	return 0
}

type DayResponse struct {
	CaptureDayTimeSeconds int64      `protobuf:"varint,1,opt,name=CaptureDayTimeSeconds,proto3" json:"CaptureDayTimeSeconds,omitempty"`
	Captures              []*Capture `protobuf:"bytes,2,rep,name=Captures,proto3" json:"Captures,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}   `json:"-"`
	XXX_unrecognized      []byte     `json:"-"`
	XXX_sizecache         int32      `json:"-"`
}

func (m *DayResponse) Reset()         { *m = DayResponse{} }
func (m *DayResponse) String() string { return proto.CompactTextString(m) }
func (*DayResponse) ProtoMessage()    {}
func (*DayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_faadcc3e9253be60, []int{2}
}

func (m *DayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DayResponse.Unmarshal(m, b)
}
func (m *DayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DayResponse.Marshal(b, m, deterministic)
}
func (m *DayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DayResponse.Merge(m, src)
}
func (m *DayResponse) XXX_Size() int {
	return xxx_messageInfo_DayResponse.Size(m)
}
func (m *DayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DayResponse proto.InternalMessageInfo

func (m *DayResponse) GetCaptureDayTimeSeconds() int64 {
	if m != nil {
		return m.CaptureDayTimeSeconds
	}
	return 0
}

func (m *DayResponse) GetCaptures() []*Capture {
	if m != nil {
		return m.Captures
	}
	return nil
}

type StartRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_faadcc3e9253be60, []int{3}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

type StartResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_faadcc3e9253be60, []int{4}
}

func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (m *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(m, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

type StopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_faadcc3e9253be60, []int{5}
}

func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (m *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(m, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

type StopResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_faadcc3e9253be60, []int{6}
}

func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (m *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(m, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Capture)(nil), "relapse_proto.Capture")
	proto.RegisterType((*DayRequest)(nil), "relapse_proto.DayRequest")
	proto.RegisterType((*DayResponse)(nil), "relapse_proto.DayResponse")
	proto.RegisterType((*StartRequest)(nil), "relapse_proto.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "relapse_proto.StartResponse")
	proto.RegisterType((*StopRequest)(nil), "relapse_proto.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "relapse_proto.StopResponse")
}

func init() {
	proto.RegisterFile("relapse.proto", fileDescriptor_faadcc3e9253be60)
}

var fileDescriptor_faadcc3e9253be60 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x2d, 0x28, 0x85, 0xa9, 0x68, 0x32, 0x89, 0x66, 0x2d, 0x1c, 0x9a, 0x9e, 0x38, 0xf5,
	0x80, 0xfe, 0x01, 0xb4, 0x41, 0x8d, 0xd1, 0x43, 0x21, 0xf1, 0x68, 0x56, 0x99, 0xc4, 0x26, 0x85,
	0x5d, 0xdb, 0x25, 0x84, 0xa3, 0xbf, 0xd8, 0xbf, 0x60, 0xdc, 0xee, 0x16, 0xc4, 0xea, 0xc1, 0x5b,
	0xdf, 0x7c, 0x6f, 0xdf, 0xbe, 0x69, 0x0b, 0xdd, 0x9c, 0x32, 0x2e, 0x0b, 0x8a, 0x64, 0x2e, 0x94,
	0x40, 0x2b, 0x9f, 0xb4, 0x0c, 0xdf, 0x1b, 0xe0, 0x5e, 0x71, 0xa9, 0x96, 0x39, 0x61, 0x1f, 0x3a,
	0xe6, 0xf1, 0x36, 0x66, 0x4e, 0xe0, 0x0c, 0x9a, 0xc9, 0x66, 0x80, 0x0c, 0xdc, 0x91, 0x94, 0x0f,
	0x7c, 0x4e, 0xac, 0x11, 0x38, 0x83, 0x4e, 0x62, 0x25, 0x06, 0xe0, 0x3d, 0xa6, 0x8b, 0x99, 0x58,
	0x4d, 0x53, 0x95, 0x11, 0x6b, 0x6a, 0xba, 0x3d, 0x42, 0x1f, 0xda, 0xe3, 0x34, 0x23, 0xc9, 0xd5,
	0x2b, 0xdb, 0xd7, 0xb8, 0xd2, 0x9a, 0x2d, 0xb3, 0x4c, 0xb3, 0x03, 0xc3, 0x8c, 0xc6, 0x08, 0xd0,
	0x14, 0x98, 0xa6, 0x73, 0x9a, 0xd0, 0x8b, 0x58, 0xcc, 0x0a, 0xd6, 0xd2, 0xd5, 0x6a, 0x08, 0x5e,
	0xc0, 0x89, 0x99, 0xc6, 0x7c, 0xbd, 0x7d, 0xc4, 0xd5, 0x47, 0xea, 0x61, 0x78, 0x09, 0x10, 0xf3,
	0x75, 0x42, 0x6f, 0x4b, 0x2a, 0xd4, 0xef, 0x19, 0xce, 0x5f, 0x19, 0x2b, 0xf0, 0x74, 0x46, 0x21,
	0xc5, 0xa2, 0xa0, 0xff, 0x85, 0xe0, 0x10, 0xda, 0x06, 0x14, 0xac, 0x11, 0x34, 0x07, 0xde, 0xf0,
	0x34, 0xfa, 0xf6, 0xb9, 0x22, 0x83, 0x93, 0xca, 0x17, 0x1e, 0xc1, 0xe1, 0x44, 0xf1, 0x5c, 0x99,
	0xfa, 0xe1, 0x31, 0x74, 0x8d, 0x2e, 0xab, 0x84, 0x5d, 0xf0, 0x26, 0x4a, 0x48, 0xcb, 0xb5, 0xff,
	0x4b, 0x96, 0x78, 0xf8, 0xe1, 0x80, 0x9b, 0x94, 0x77, 0xe0, 0x3d, 0xe0, 0x35, 0x29, 0x1b, 0x3d,
	0x16, 0xf9, 0x28, 0xe6, 0x6b, 0x3c, 0xdb, 0xe9, 0xb0, 0x79, 0x57, 0xbe, 0x5f, 0x87, 0xcc, 0xbd,
	0x7b, 0x78, 0x67, 0xaa, 0xd9, 0xff, 0xab, 0xb7, 0xe3, 0xde, 0xee, 0xed, 0xf7, 0xeb, 0x61, 0x15,
	0x76, 0x53, 0xae, 0x61, 0xb3, 0xfc, 0x1f, 0xf6, 0x6a, 0x45, 0xbf, 0x57, 0xcb, 0x6c, 0xd2, 0x73,
	0x4b, 0x4f, 0xcf, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x10, 0x88, 0x3a, 0xb8, 0x19, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RelapseClient is the client API for Relapse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RelapseClient interface {
	GetCapturesForADay(ctx context.Context, in *DayRequest, opts ...grpc.CallOption) (*DayResponse, error)
	StartCapture(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	StopCapture(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type relapseClient struct {
	cc grpc.ClientConnInterface
}

func NewRelapseClient(cc grpc.ClientConnInterface) RelapseClient {
	return &relapseClient{cc}
}

func (c *relapseClient) GetCapturesForADay(ctx context.Context, in *DayRequest, opts ...grpc.CallOption) (*DayResponse, error) {
	out := new(DayResponse)
	err := c.cc.Invoke(ctx, "/relapse_proto.Relapse/GetCapturesForADay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relapseClient) StartCapture(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/relapse_proto.Relapse/StartCapture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relapseClient) StopCapture(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, "/relapse_proto.Relapse/StopCapture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelapseServer is the server API for Relapse service.
type RelapseServer interface {
	GetCapturesForADay(context.Context, *DayRequest) (*DayResponse, error)
	StartCapture(context.Context, *StartRequest) (*StartResponse, error)
	StopCapture(context.Context, *StopRequest) (*StopResponse, error)
}

// UnimplementedRelapseServer can be embedded to have forward compatible implementations.
type UnimplementedRelapseServer struct {
}

func (*UnimplementedRelapseServer) GetCapturesForADay(ctx context.Context, req *DayRequest) (*DayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapturesForADay not implemented")
}
func (*UnimplementedRelapseServer) StartCapture(ctx context.Context, req *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCapture not implemented")
}
func (*UnimplementedRelapseServer) StopCapture(ctx context.Context, req *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopCapture not implemented")
}

func RegisterRelapseServer(s *grpc.Server, srv RelapseServer) {
	s.RegisterService(&_Relapse_serviceDesc, srv)
}

func _Relapse_GetCapturesForADay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelapseServer).GetCapturesForADay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relapse_proto.Relapse/GetCapturesForADay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelapseServer).GetCapturesForADay(ctx, req.(*DayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relapse_StartCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelapseServer).StartCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relapse_proto.Relapse/StartCapture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelapseServer).StartCapture(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relapse_StopCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelapseServer).StopCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relapse_proto.Relapse/StopCapture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelapseServer).StopCapture(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Relapse_serviceDesc = grpc.ServiceDesc{
	ServiceName: "relapse_proto.Relapse",
	HandlerType: (*RelapseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapturesForADay",
			Handler:    _Relapse_GetCapturesForADay_Handler,
		},
		{
			MethodName: "StartCapture",
			Handler:    _Relapse_StartCapture_Handler,
		},
		{
			MethodName: "StopCapture",
			Handler:    _Relapse_StopCapture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relapse.proto",
}
